//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM2Randomizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM2Randomizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Also randomize the &quot;Dr. WILY&quot;?
        ///# DR. COSSACK
        ///# DR. LIGHT
        ///# MR. X
        ///# BREAK MAN
        ///# DOC ROBOT
        ///# BASS
        ///#
        ///# Misc
        ///CLASH
        ///WILY
        ///PROTO
        ///BREAK
        ///ROCK
        ///DARK
        ///ENKER
        ///QUINT
        ///PUNK
        ///BALLADE
        ///#
        ///# Mega Man
        ///CUT
        ///ELEC
        ///ICE
        ///FIRE
        ///BOMB
        ///GUTS
        ///#
        ///# Mega Man 2
        ///BUBBLE
        ///HEAT
        ///METAL
        ///AIR
        ///FLASH
        ///QUICK
        ///WOOD
        ///CRASH
        ///#
        ///# MEGA MAN 3
        ///TOP
        ///GEMINI
        ///SHADOW
        ///NEEDLE
        ///HARD
        ///MAGNET
        ///SNAKE
        ///SPARK
        ///#
        ///# MEGA MAN 4
        ///PHARAOH
        ///BRIGHT
        ///RING
        ///DUST
        ///SKULL
        ///DIVE
        ///DRILL
        ///TOAD
        ///#
        ///# MEGA MAN 5
        ///STAR
        ///GRAVITY
        ///GYRO
        ///CRYSTAL
        ///NAPALM
        ///STONE
        ///C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bossnames {
            get {
                return ResourceManager.GetString("bossnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUDSON SOFT
        ///NINTENDO
        ///TREASURE
        ///KONAMI
        ///DATA EAST
        ///SNK PLAYMORE
        ///ACTIVISION
        ///JALECO
        ///TECMO
        ///SUNSOFT
        ///TAITO
        ///SONY
        ///SEGA CO.LTD
        ///IREM
        ///COMPILE
        ///KOEI
        ///TENGEN
        ///KEMCO
        ///RARE
        ///ATLUS
        ///HALKEN
        ///LUCASARTS
        ///WESTWOOD
        ///INTERPLAY
        ///TOSE CO.LTD
        ///NAMCO LTD.
        ///NATSUME
        ///SQUARE CO.LTD
        ///COMCEPT
        ///INTI CREATES
        ///RAINBOW ARTS
        ///OCEAN LTD.
        ///FACTOR 5
        ///VIC TOKAI
        ///ASCII
        ///THQ
        ///QUINTET
        ///ENIX
        ///MINDSCAPE.
        /// </summary>
        internal static string companynames {
            get {
                return ResourceManager.GetString("companynames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AFGHANISTAN
        ///ALBANIA
        ///ALGERIA
        ///ANDORRA
        ///ANGOLA
        ///ANTIGUA AND BARBUDA
        ///ARGENTINA
        ///ARMENIA
        ///ARUBA
        ///AUSTRALIA
        ///AUSTRIA
        ///AZERBAIJAN
        ///ANTARCTICA
        ///THE BAHAMAS
        ///BAHRAIN
        ///BANGLADESH
        ///BARBADOS
        ///BELARUS
        ///BELGIUM
        ///BELIZE
        ///BENIN
        ///BHUTAN
        ///BOLIVIA
        ///BOSNIA AND HERZEGOVINA
        ///BOTSWANA
        ///BRAZIL
        ///BRUNEI
        ///BULGARIA
        ///BURKINA FASO
        ///BURMA
        ///BURUNDI
        ///CAMBODIA
        ///CAMEROON
        ///CANADA
        ///CABO VERDE
        ///CENTRAL AFRICAN REPUBLIC
        ///CHAD
        ///CHILE
        ///CHINA
        ///COLOMBIA
        ///THE CONGO
        ///COSTA RICA
        ///CROATIA
        ///CUBA
        ///CURACAO
        ///CYPRUS
        ///CZECH REPUBLIC
        ///DENMARK
        ///DJIBOUTI
        ///DO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string countrylist {
            get {
                return ResourceManager.GetString("countrylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14|09|MM2 RANDOMIZER
        ///13|2A|ROBOT MASTERS
        ///01|61|f
        ///17|AB|P H A W B Q F M C
        ///25|E3|HEATMAN 2   3     1     2
        ///24|24|AIRMAN 1 2   1 2       4
        ///25|63|WOODMAN 1   1 1 3 2      
        ///27|A1|BUBBLEMAN 2 4   1 1 3   1  
        ///26|E2|QUICKMAN 1 5 1 1 1     2  
        ///26|22|FLASHMAN 1 2   1   1   3 1
        ///26|62|METALMAN 1 2 1 2   1 1 1  
        ///26|A2|CLASHMAN 1 2 2 3 1        
        ///01|E1|f
        ///01|21|f
        ///11|6B|WILY BOSSES
        ///01|A1|f
        ///15|2C|P H A W B Q M C
        ///22|65|DRAGON                
        ///24|A3|PICOPICO                
        ///20|E7|GUTS                
        ///23|24|B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string creditstext {
            get {
                return ResourceManager.GetString("creditstext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Index,StageNum,RoomNum,ScreenNum,IsActive,EnemyID,XPosOriginal,YPosOriginal,YPosAir,YPosGround,FaceRight
        ///00,00,00,01,true,2B,70,10,14,B4,false
        ///01,00,00,01,true,2B,F0,10,14,B4,false
        ///02,00,00,02,true,2B,90,10,18,B4,false
        ///03,00,00,02,true,21,A8,58,58,58,false
        ///04,00,00,02,true,21,E8,78,78,78,false
        ///05,00,00,03,true,21,48,48,48,48,false
        ///06,00,00,03,true,21,88,68,68,68,false
        ///07,00,00,03,true,21,D8,98,98,98,false
        ///08,00,00,04,true,21,28,58,58,58,false
        ///09,00,00,04,true,21,88,58,58,58,false
        ///0A,00,00,04,tru [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string enemylist {
            get {
                return ResourceManager.GetString("enemylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #EnemyName,#OffsetHex,#P,#H,#A,#W,#B,#Q,#C,#M
        ///Shrink               ,00,7,20,0,10,20,7,10,10
        ///Shrink(From Angler)  ,01,7,20,0,10,20,7,10,10
        ///Claw(Instance)       ,08,20,20,10,10,20,7,10,10
        ///Tanishi	             ,0A,10,20,0,10,0,4,10,4
        ///Kerog                ,0C,2,20,0,0,4,4,0,2
        ///Kerog(Small)         ,0D,20,20,10,10,20,20,10,10
        ///Batton               ,16,10,20,10,10,0,10,10,20
        ///Robbit               ,17,2,20,0,20,7,4,20,4
        ///Friender(Instance)   ,19,1,20,0,20,0,2,0,2
        ///Monking              ,1D,7,20,0,20,0,7,20,7
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string enemyweakness {
            get {
                return ResourceManager.GetString("enemyweakness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MM2 {
            get {
                object obj = ResourceManager.GetObject("MM2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] mm2rng_prepatch {
            get {
                object obj = ResourceManager.GetObject("mm2rng_prepatch", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Mega Man 2 Song Interpreter
        ///#
        ///# Each line is one song, and of comma-separated value format
        ///#
        ///# Example:
        ///# SongName,OriginalStartAddress,SongData
        ///#	where   
        ///#		SongName = Any string to identify the song, such as the name and what game/hack it comes from
        ///#		OriginalStartAddress = The address of the first byte of the song&apos;s header (value 0F) in the song&apos;s original ROM
        ///#		SongData = Stream of bytes representing the song, each byte a pair of adjacent characters in the string
        ///#
        ///# The 10 songs chosen  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string music {
            get {
                return ResourceManager.GetString("music", resourceCulture);
            }
        }
    }
}
