//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM2Randomizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM2RandoLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Also randomize the &quot;Dr. WILY&quot;?
        ///# DR. COSSACK
        ///# DR. LIGHT
        ///# MR. X
        ///# BREAK MAN
        ///# DOC ROBOT
        ///# BASS
        ///#
        ///# Misc
        ///CLASH
        ///WILY
        ///PROTO
        ///BREAK
        ///ROCK
        ///DARK
        ///ENKER
        ///QUINT
        ///PUNK
        ///BALLADE
        ///#
        ///# Mega Man
        ///CUT
        ///ELEC
        ///ICE
        ///FIRE
        ///BOMB
        ///GUTS
        ///#
        ///# Mega Man 2
        ///BUBBLE
        ///HEAT
        ///METAL
        ///AIR
        ///FLASH
        ///QUICK
        ///WOOD
        ///CRASH
        ///#
        ///# MEGA MAN 3
        ///TOP
        ///GEMINI
        ///SHADOW
        ///NEEDLE
        ///HARD
        ///MAGNET
        ///SNAKE
        ///SPARK
        ///#
        ///# MEGA MAN 4
        ///PHARAOH
        ///BRIGHT
        ///RING
        ///DUST
        ///SKULL
        ///DIVE
        ///DRILL
        ///TOAD
        ///#
        ///# MEGA MAN 5
        ///STAR
        ///GRAVITY
        ///GYRO
        ///CRYSTAL
        ///NAPALM
        ///STONE
        ///C [rest of string was truncated]&quot;;.
        /// </summary>
        public static string bossnames {
            get {
                return ResourceManager.GetString("bossnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;CompanyNameSet&gt;
        ///    &lt;CompanyName&gt;
        ///        &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///        &lt;Name&gt;HUDSON SOFT&lt;/Name&gt;
        ///    &lt;/CompanyName&gt;
        ///    &lt;CompanyName&gt;
        ///        &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///        &lt;Name&gt;NINTENDO&lt;/Name&gt;
        ///    &lt;/CompanyName&gt;
        ///    &lt;CompanyName&gt;
        ///        &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///        &lt;Name&gt;TREASURE&lt;/Name&gt;
        ///    &lt;/CompanyName&gt;
        ///    &lt;CompanyName&gt;
        ///        &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///        &lt;Name&gt;KONAMI&lt;/Name&gt;
        ///    &lt;/CompanyName&gt;
        ///    &lt;CompanyName&gt;
        ///        &lt;Enabled&gt;tr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CompanyNameConfig {
            get {
                return ResourceManager.GetString("CompanyNameConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;CountryNameSet&gt;
        ///    &lt;CountryName&gt;
        ///        &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///        &lt;Name&gt;AFGHANISTAN&lt;/Name&gt;
        ///    &lt;/CountryName&gt;
        ///    &lt;CountryName&gt;
        ///        &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///        &lt;Name&gt;ALBANIA&lt;/Name&gt;
        ///    &lt;/CountryName&gt;
        ///    &lt;CountryName&gt;
        ///        &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///        &lt;Name&gt;ALGERIA&lt;/Name&gt;
        ///    &lt;/CountryName&gt;
        ///    &lt;CountryName&gt;
        ///        &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///        &lt;Name&gt;ANDORRA&lt;/Name&gt;
        ///    &lt;/CountryName&gt;
        ///    &lt;CountryName&gt;
        ///        &lt;Enabled&gt;tru [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CountryNameConfig {
            get {
                return ResourceManager.GetString("CountryNameConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;CreditTextSet&gt;
        ///    &lt;CreditText&gt;
        ///        &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///        &lt;Value&gt;09&lt;/Value&gt;
        ///        &lt;Text&gt;MM2 RANDOMIZER&lt;/Text&gt;
        ///    &lt;/CreditText&gt;
        ///    &lt;CreditText&gt;
        ///        &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///        &lt;Value&gt;2A&lt;/Value&gt;
        ///        &lt;Text&gt;ROBOT MASTERS&lt;/Text&gt;
        ///    &lt;/CreditText&gt;
        ///    &lt;CreditText&gt;
        ///        &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///        &lt;Value&gt;61&lt;/Value&gt;
        ///        &lt;Text&gt;f&lt;/Text&gt;
        ///    &lt;/CreditText&gt;
        ///    &lt;CreditText&gt;
        ///        &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///        &lt;Valu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CreditTextConfig {
            get {
                return ResourceManager.GetString("CreditTextConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;EnemySet&gt;
        ///    &lt;!--
        ///        Heat Man / Wily 1 Stage
        ///    --&gt;
        ///    &lt;Enemy&gt;
        ///        &lt;Index&gt;00&lt;/Index&gt;
        ///        &lt;StageNumber&gt;00&lt;/StageNumber&gt;
        ///        &lt;RoomNumber&gt;00&lt;/RoomNumber&gt;
        ///        &lt;ScreenNumber&gt;01&lt;/ScreenNumber&gt;
        ///        &lt;IsActive&gt;true&lt;/IsActive&gt;
        ///        &lt;EnemyId&gt;2B&lt;/EnemyId&gt;
        ///        &lt;PositionX&gt;70&lt;/PositionX&gt;
        ///        &lt;PositionY&gt;10&lt;/PositionY&gt;
        ///        &lt;PositionAir&gt;24&lt;/PositionAir&gt;
        ///        &lt;PositionGround&gt;A4&lt;/PositionGround&gt;
        ///        &lt;FaceRight&gt;false&lt;/Fa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EnemySet {
            get {
                return ResourceManager.GetString("EnemySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;EnemyWeaknessSet&gt;
        ///    &lt;EnemyWeakness&gt;
        ///        &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///        &lt;Name&gt;Shrink&lt;/Name&gt;
        ///        &lt;Offset&gt;00&lt;/Offset&gt;
        ///        &lt;Buster&gt;7&lt;/Buster&gt;
        ///        &lt;Heat&gt;20&lt;/Heat&gt;
        ///        &lt;Air&gt;0&lt;/Air&gt;
        ///        &lt;Wood&gt;10&lt;/Wood&gt;
        ///        &lt;Bubble&gt;20&lt;/Bubble&gt;
        ///        &lt;Quick&gt;7&lt;/Quick&gt;
        ///        &lt;Crash&gt;10&lt;/Crash&gt;
        ///        &lt;Metal&gt;10&lt;/Metal&gt;
        ///    &lt;/EnemyWeakness&gt;
        ///    &lt;EnemyWeakness&gt;
        ///        &lt;Enabled&gt;false&lt;/Enabled&gt;
        ///        &lt;Name&gt;Shrink (From Angler)&lt;/Name&gt;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EnemyWeaknessSet {
            get {
                return ResourceManager.GetString("EnemyWeaknessSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;IntroStorySet&gt;
        ///    &lt;!-- Castlevania III: Dracula&apos;s Curse --&gt;
        ///    &lt;IntroStory&gt;
        ///        &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///        &lt;Lines&gt;
        ///            &lt;Line&gt;DURING 15TH CENTURY EUROPE &lt;/Line&gt;
        ///            &lt;Line&gt;  THERE LIVED A PERSON     &lt;/Line&gt;
        ///            &lt;Line&gt;    NAMED DRACULA. HE      &lt;/Line&gt;
        ///            &lt;Line&gt;PRACTICED SORCERY IN ORDER &lt;/Line&gt;
        ///            &lt;Line&gt;   TO CREATE A BAD WORLD   &lt;/Line&gt;
        ///            &lt;Line&gt;     FILLED WITH EVIL.     &lt;/Line&gt;
        ///            &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IntroStoryConfig {
            get {
                return ResourceManager.GetString("IntroStoryConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;LevelComponents&quot;: [
        ///      {
        ///        &quot;Name&quot;: &quot;flash_room0_screen2&quot;,
        ///        &quot;StartAddress&quot;: &quot;14590&quot;,
        ///        &quot;EndAddress&quot;: &quot;145CF&quot;,
        ///        &quot;Variations&quot;: [
        ///          {
        ///            &quot;Name&quot;: &quot;default&quot;,
        ///            &quot;TsaMap&quot;: [
        ///              &quot;59&quot;,&quot;2A&quot;,&quot;28&quot;,&quot;01&quot;,&quot;01&quot;,&quot;23&quot;,&quot;58&quot;,&quot;59&quot;, 
        ///              &quot;6B&quot;,&quot;33&quot;,&quot;25&quot;,&quot;1B&quot;,&quot;03&quot;,&quot;25&quot;,&quot;45&quot;,&quot;67&quot;, 
        ///              &quot;59&quot;,&quot;60&quot;,&quot;30&quot;,&quot;09&quot;,&quot;03&quot;,&quot;75&quot;,&quot;78&quot;,&quot;03&quot;, 
        ///              &quot;59&quot;,&quot;23&quot;,&quot;2D&quot;,&quot;10&quot;,&quot;03&quot;,&quot;17&quot;,&quot;09&quot;,&quot;71&quot;, 
        ///              &quot;61&quot;,&quot;29&quot;,&quot;22&quot;,&quot;0D&quot;,&quot;03&quot;,&quot;33&quot;,&quot;0B [rest of stri....
        /// </summary>
        public static string level_components {
            get {
                return ResourceManager.GetString("level_components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] mm2rng_musicpatch {
            get {
                object obj = ResourceManager.GetObject("mm2rng_musicpatch", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] mm2rng_prepatch {
            get {
                object obj = ResourceManager.GetObject("mm2rng_prepatch", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;!--
        ///    Mega Man 2 Sound Track Config File
        ///
        ///    SongName = Any string to identify the song, such as the name and what game/hack it comes from
        ///    OriginalStartAddress = The address of the first byte of the song&apos;s header (value 0F) in the song&apos;s original ROM
        ///    SongData = Stream of bytes representing the song, each byte a pair of adjacent characters in the string
        ///
        ///    The 11 songs chosen for stages should not exceed 9438 (0x24DE) total bytes. Don&apos;t make too [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SoundTrackConfiguration {
            get {
                return ResourceManager.GetString("SoundTrackConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpriteSwap_Bass {
            get {
                object obj = ResourceManager.GetObject("SpriteSwap_Bass", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpriteSwap_Proto {
            get {
                object obj = ResourceManager.GetObject("SpriteSwap_Proto", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpriteSwap_Roll {
            get {
                object obj = ResourceManager.GetObject("SpriteSwap_Roll", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
